package object

const (
	INTEGER  = "INTEGER"
	BOOLEAN  = "BOOLEAN"
	ARRAY    = "ARRAY"
	NULL     = "NULL"
	RETURN   = "RETURN"
	ERROR    = "ERROR"
	FUNCTION = "FUNCTION"
	STRING   = "STRING"
	BUILTIN  = "BUILTIN"
	METHOD   = "METHOD"
)
